from django.urls import path

from .views import (
    DisplacementDetailAPIView,
    DisplacementExportAPIView,
    DisplacementImportAPIView,
    DisplacementImportDetailAPIView,
    DisplacementImportListAPIView,
    DisplacementListCreateAPIView,
    DisplacementReverifyAPIView,
    DisplacementStatsAPIView,
    DisplacementUniqueFiltersAPIView,
)

urlpatterns = [
    path(
        "displacements/",
        DisplacementListCreateAPIView.as_view(),
        name="displacement-list-create",
    ),
    path(
        "displacements/stats/",
        DisplacementStatsAPIView.as_view(),
        name="displacement-stats",
    ),
    path(
        "displacements/import/",
        DisplacementImportAPIView.as_view(),
        name="displacement-import",
    ),
    path(
        "displacements/import-list/",
        DisplacementImportListAPIView.as_view(),
        name="displacement-import-list",
    ),
    path(
        "displacements/import-list/<int:pk>/",
        DisplacementImportDetailAPIView.as_view(),
        name="displacement-import-detail",
    ),
    path(
        "displacements/export/",
        DisplacementExportAPIView.as_view(),
        name="displacement-export",
    ),
    path(
        "displacements/unique-filters/",
        DisplacementUniqueFiltersAPIView.as_view(),
        name="displacement-unique-filters",
    ),
    path(
        "displacements/<int:pk>/",
        DisplacementDetailAPIView.as_view(),
        name="displacement-detail",
    ),
    path(
        "displacements/<int:pk>/reverify/",
        DisplacementReverifyAPIView.as_view(),
        name="displacement-reverify",
    ),
]
