# Generated by Django 6.0.6 on 2026-08-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='villageassessment',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('returned', 'Returned')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='villageassessment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_village_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villageassessment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_village_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='villageassessment',
            index=models.Index(fields=['status'], name='village_ass_status_ff0150_idx'),
        ),
    ]
