# Generated by Django 6.0.6 on 2026-08-14 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement', '0004_displacementimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='displacement',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('returned', 'Returned')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='displacement',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_displacements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='displacement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_displacements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='displacement',
            index=models.Index(fields=['status'], name='displacemen_status_4b5105_idx'),
        ),
    ]
