# Generated by Django 6.0.6 on 2026-08-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
