from django.urls import path

from .views import (
    EvacuationCentreDetailAPIView,
    EvacuationCentreExportAPIView,
    EvacuationCentreImportAPIView,
    EvacuationCentreImportDetailAPIView,
    EvacuationCentreImportListAPIView,
    EvacuationCentreListCreateAPIView,
    EvacuationCentreMinimalListAPIView,
    EvacuationCentreSearchAPIView,
    EvacuationCentreStatsAPIView,
    EvacuationCentreReverifyAPIView,
)

urlpatterns = [
    path(
        "evacuation-centres/",
        EvacuationCentreListCreateAPIView.as_view(),
        name="evacuation-centre-list-create",
    ),
    path(
        "evacuation-centres/location/",
        EvacuationCentreMinimalListAPIView.as_view(),
        name="evacuation-centre-minimal-list",
    ),
    path(
        "evacuation-centres/search/",
        EvacuationCentreSearchAPIView.as_view(),
        name="evacuation-centre-search",
    ),
    path(
        "evacuation-centres/import/",
        EvacuationCentreImportAPIView.as_view(),
        name="evacuation-centre-import",
    ),
    path(
        "evacuation-centres/import-list/",
        EvacuationCentreImportListAPIView.as_view(),
        name="evacuation-centre-import-list",
    ),
    path(
        "evacuation-centres/import-list/<int:pk>/",
        EvacuationCentreImportDetailAPIView.as_view(),
        name="evacuation-centre-import-detail",
    ),
    path(
        "evacuation-centres/export/",
        EvacuationCentreExportAPIView.as_view(),
        name="evacuation-centre-export",
    ),
    path(
        "evacuation-centres/stats/",
        EvacuationCentreStatsAPIView.as_view(),
        name="evacuation-centre-stats",
    ),
    path(
        "evacuation-centres/<int:pk>/",
        EvacuationCentreDetailAPIView.as_view(),
        name="evacuation-centre-detail",
    ),
    path(
        "evacuation-centres/<int:pk>/reverify/",
        EvacuationCentreReverifyAPIView.as_view(),
        name="evacuation-centre-reverify",
    ),
]
