# Generated by Django 6.0.6 on 2026-08-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityLevelDamageAssessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Level Damage Assessment Form',
                'verbose_name_plural': 'Community Level Damage Assessment Forms',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DamageAssessmentFormCommunityV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Damage Assessment Form (Community V2)',
                'verbose_name_plural': 'Damage Assessment Forms (Community V2)',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplacementProfilePhoneSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Displacement Profile - Phone Survey',
                'verbose_name_plural': 'Displacement Profile - Phone Surveys',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplacementTrackingMatrixForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Displacement Tracking Matrix Form',
                'verbose_name_plural': 'Displacement Tracking Matrix Forms',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DurableSolutionRelocationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Durable Solution & Relocation Survey',
                'verbose_name_plural': 'Durable Solution & Relocation Surveys',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RapidAssessmentFormAreaCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rapid Assessment Form (Area Council)',
                'verbose_name_plural': 'Rapid Assessment Forms (Area Council)',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMonitoringTool2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, default=dict, help_text='Form field definitions and schema configuration.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Submitted data and form responses.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Monitoring Tool 2026',
                'verbose_name_plural': 'Service Monitoring Tools 2026',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
